FROM node:18-alpine 

WORKDIR /app  

COPY package.json package-lock.json ./
RUN npm install --force
RUN npm install @fortawesome/react-fontawesome @fortawesome/free-solid-svg-icons --force
RUN npm install @react-three/drei --legacy-peer-deps 
RUN npm install react-chartjs-2 chart.js --force

COPY . .

COPY ./certificates/localhost.pem /etc/ssl/certs/localhost.pem
COPY ./certificates/localhost-key.pem /etc/ssl/private/localhost-key.pem

RUN npm run build 

EXPOSE 3000
EXPOSE 8443

ENV NODE_ENV=development

#CMD ["npm", "run", "start"]
CMD ["npm", "run", "dev", "--", "--https", "--cert", "/etc/ssl/certs/localhost.pem", "--key", "/etc/ssl/private/localhost-key.pem"]
