version: "3.8"

services:
  frontend:
    image: afabica234/myapp-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    image: afabica234/myapp-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: always

