apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default  # ✅ Explicitly set namespace
  labels: 
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: myapp-frontend-secret
      containers:
        - name: frontend
          image: index.docker.io/afabica234/myapp-frontend:latest
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default  # ✅ Ensure service is also in the default namespace
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

