name: Build and Deploy Locally

on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main 

jobs:
  build-and-deploy:
  runs-on: ubuntu-22.04

  steps: 
  -name: Checkout Code
  uses: actions/checkout@v3

  -name: Set Up Docker 
  uses: docker/setup-buildx-action@v2 

  -name: built and run application locally in docker 
   run: |
    docker-compose down --remove-orphans
    docker-compose build 
    docker-compose up -d 

  -name: Test Backend 
   run: | 
    docker exec springboot-backend gradle test 

  -name: Test Frontend
   run: |
    docker exec nextjs-frontend npm run test 
