apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-container
          image: springboot-image
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
  progressDeadLineSeconds: 600 # Increased progress deadline 

