#apiVersion: v1
#kind: Service
#metadata: 
#  name: frontend-service
#spec: 
#  selector: 
#    app: frontend
#  ports:  
#    - protocol: TCP 
#      port: 80
#      targetPort: 3000 
#  type: LoadBalancer
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend-service
#spec:
#  type: NodePort
#  ports:
#    - port: 443
#      targetPort: 443
#      nodePort: 30080   # Example: Exposing on port 30080 on your machine
#  selector:
#    app: frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP  # Corrected to ClusterIP (internal access within the cluster)


