apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: tls-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: tls-keys
              mountPath: /etc/ssl/private
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
        - name: tls-certs
          secret:
            secretName: my-tls-secret
            items:
              - key: tls.crt
                path: tls.crt
        - name: tls-keys
          secret:
            secretName: my-tls-secret
            items:
              - key: tls.key
                path: tls.key

